### ISSUE TITLE
Suggestion: Add prettier and replace tslint with eslint

### ISSUE THREAD

**Issue by redd29** [kumaranshu72/spotter#14]
Add prettier so as to have proper coding style in the project, which doesn't conflict with each developer's coding environment. I'd suggest adding prettier and eslint, since they both work very well together and give devs a easy time. Let me know if you approve of this, and I'll make a PR

**Comment by kumaranshu72** [comment]
Tslint is already there. you can go for prettier. Also add git hook to check for lint and prettier issues.

**Comment by mythio** [comment]
I haven't tried prettier with tslint, eslint along with prettier works great! It will automatically format the code as per your linting preference.

**Comment by kumaranshu72** [comment]
Ok go ahead with tslint and prettier

**Comment by ghost** [comment]
I tried adding prettier but, the project as of now, uses several deprecated tslint rules, and thus the project needs a refactor to go with prettier. Idk if that is okay from your side, till then. I will put this on hold.

**Comment by kumaranshu72** [comment]
I guess you were replacing tslint with eslint?
